import { Appointment, AppointmentPriority, AppointmentStatus } from '../entities/appointment.entity';
import { IdCard } from '../value-objects/id-card.value-object';

/**
 * Pattern: Domain Factory
 * Encapsulates the creation logic and default policies for Appointments.
 */
export class AppointmentFactory {
    /**
     * Creates a new pending appointment with default business rules.
     */
    public static createNew(
        idCard: IdCard,
        fullName: string,
        priority: AppointmentPriority = 'medium'
    ): Appointment {
        // ⚕️ HUMAN CHECK - Business Policy: 
        // New appointments default to 'waiting' status.
        const defaultStatus: AppointmentStatus = 'waiting';

        return new Appointment(
            '', // ID will be generated by persistence or later in context
            idCard,
            fullName,
            priority,
            defaultStatus,
            null,
            Date.now()
        );
    }
}
