"""agentic-flow CLI: af init | reindex | run | build | metrics"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

from . import detect_local, logger, memory, orchestrator, prometheus, resources, router, schema, warmup

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT.parent

# --- Bridge templates (generated by `af init`) ---

_CLAUDE_MD = """\
# agentic-flow

Pipeline agentic híbrido (local + cloud). Spec-driven, memoria incremental, budget guard, mínimo-token.

## Reglas

1. No escribir código sin solicitud explícita.
2. No modificar lógica existente sin aprobación.
3. Si la solicitud es ambigua, preguntar antes de actuar.
4. Explicar en una línea antes de cada acción.
5. Diffs unificados sobre archivos completos.
6. Output: artefactos + 1 línea de resumen. Sin emojis, sin narración.

## Pipeline

```bash
./.agentic-flow/af init
./.agentic-flow/af reindex
./.agentic-flow/af run <agent> "<task>"
./.agentic-flow/af build <feature>
./.agentic-flow/af metrics
```

## Specs

Toda funcionalidad nueva requiere spec en `.agentic-flow/specs/<feature>.spec.md`.
Lifecycle: DRAFT → REVIEW → APPROVED → IMPLEMENTED.

## Configuración

- Routing: `.agentic-flow/config/routing.yaml`
- Budget: `.agentic-flow/config/budget.yaml`
- Agentes: `.agentic-flow/config/agents.yaml`
- Reglas: `.agentic-flow/rules/`
- Memoria: `.agentic-flow/memory/`
"""

_COPILOT_INSTRUCTIONS = """\
# Copilot Instructions

Este repositorio usa **agentic-flow**: pipeline agentic híbrido (local + cloud) con specs, memoria incremental y budget guard.

## Cómo trabajar

- Toda nueva funcionalidad pasa por una spec en `.agentic-flow/specs/`.
- Pipeline: `./.agentic-flow/af <cmd>`.
- Config: `.agentic-flow/config/` — routing, budget, agentes.
- Reglas: `.agentic-flow/rules/`.
- Memoria: `.agentic-flow/memory/`.

## Reglas de oro

1. No escribir código sin solicitud explícita.
2. No modificar lógica existente sin aprobación.
3. Si la solicitud es ambigua, preguntar antes de actuar.
4. Explicar en una línea antes de cada acción.
5. Diffs unificados sobre archivos completos.
6. Output: artefactos + 1 línea de resumen. Sin emojis, sin narración.

## Comandos

```bash
./.agentic-flow/af init
./.agentic-flow/af reindex
./.agentic-flow/af run <agent> "<task>"
./.agentic-flow/af build <feature>
./.agentic-flow/af metrics
```
"""

_AGENT_MD = """\
---
name: agentic-flow
description: "Pipeline agentic híbrido (local + cloud) con specs, memoria incremental y budget guard."
tools:
  - run_in_terminal
  - read_file
  - replace_string_in_file
  - create_file
  - file_search
  - grep_search
  - semantic_search
---

Eres **agentic-flow**, el agente orquestador de este proyecto.

## Flujo

1. Funcionalidad nueva → spec primero (`.agentic-flow/specs/<feature>.spec.md`).
2. Spec lifecycle: DRAFT → REVIEW → APPROVED → IMPLEMENTED.
3. Ejecutar: `./.agentic-flow/af build <feature>` o `./.agentic-flow/af run <agent> "<task>"`.
4. Reportar: una línea con archivos modificados y tokens/USD.

## Reglas

- No código sin solicitud. No modificar sin aprobación. Preguntar si ambiguo.
- Diffs unificados. Output: artefactos + 1 línea. Sin emojis.
- Determinismo: temperature=0, seed=42.
- Budget guard: si excede USD/día → tier local.

## Agentes

spec-generator, backend, frontend, database, test-backend, test-frontend, qa, documentation, orchestrator.
"""

_CLAUDE_SETTINGS = """\
{
  "permissions": {
    "allow": [
      "Bash(./.agentic-flow/af:*)",
      "Bash(python3 -m unittest:*)",
      "Read(.agentic-flow/**)",
      "Edit(.agentic-flow/specs/**)",
      "Edit(.agentic-flow/memory/**)",
      "Edit(.agentic-flow/runtime/**)"
    ],
    "deny": []
  }
}
"""

_SKILL_MD = """\
---
name: agentic-flow
description: Pipeline agentic híbrido (local + cloud) con specs, memoria incremental y budget guard.
---

# Skill: agentic-flow

Ejecuta el pipeline via `./.agentic-flow/af <cmd>`.

## Cuándo activar

- Usuario pide funcionalidad nueva, refactor, o tarea de desarrollo.
- Menciona: /agentic-flow, af, spec, pipeline, o nombres de agentes.

## Procedimiento

1. Funcionalidad nueva → spec primero.
2. Spec en APPROVED → implementar.
3. Ejecutar: `./.agentic-flow/af build <feature>` o `run <agent> "<task>"`.
4. Reportar: archivos + tokens/USD.

## Reglas

- Contexto mínimo por agente.
- Determinismo (temperature=0, seed=42).
- Budget guard activo.
- Diffs, no archivos completos.
- Sin emojis, sin narración.
"""

_PROMPT_MD = """\
---
description: Ejecuta el pipeline agentic-flow para una funcionalidad o tarea.
---

# /agentic-flow

Orquesta el pipeline **agentic-flow**: spec → implementación → tests → QA.

## Flujo

1. Funcionalidad nueva → generar spec en `.agentic-flow/specs/<feature>.spec.md`.
2. Validar: status APPROVED antes de implementar.
3. `./.agentic-flow/af build <feature>` o `./.agentic-flow/af run <agent> "<task>"`.
4. Reportar: artefactos + métricas.

## Reglas

- Diffs unificados. Sin emojis. 1 línea de resumen.
- Budget guard: USD/día excedido → tier local.
- Determinismo: temperature=0, seed=42.
"""


def _ensure_bridges() -> list[str]:
    """Generate editor bridge files if they don't exist. Returns list of created paths."""
    created = []
    bridges = [
        (PROJECT / "CLAUDE.md", _CLAUDE_MD),
        (PROJECT / ".github" / "copilot-instructions.md", _COPILOT_INSTRUCTIONS),
        (PROJECT / ".github" / "agents" / "agentic-flow.agent.md", _AGENT_MD),
        (PROJECT / ".github" / "prompts" / "agentic-flow.prompt.md", _PROMPT_MD),
        (PROJECT / ".claude" / "settings.json", _CLAUDE_SETTINGS),
        (PROJECT / ".claude" / "skills" / "agentic-flow" / "SKILL.md", _SKILL_MD),
    ]
    for path, content in bridges:
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            created.append(str(path.relative_to(PROJECT)))
    return created


def _cmd_init(_) -> int:
    # 1. Detect local models.
    print(json.dumps(detect_local.detect_all(), indent=2)[:400])
    detect_local.main()

    # 2. Profile system resources and generate usage conditions.
    res = resources.snapshot()
    profile = resources.generate_system_profile(res)
    profile_path = ROOT / "runtime" / "system-profile.json"
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(json.dumps(profile, indent=2))
    print(f"system: ram={res.ram_total_mb}MB cpu={res.cpu_count}cores "
          f"gpu={'yes' if res.gpu_vram_total_mb else 'no'} "
          f"profile={profile['execution_mode']}")

    # 3. Seed memory files.
    memory.MEMORY.mkdir(parents=True, exist_ok=True)
    for name in ("project-context.md", "domain.md", "conventions.md", "architecture.md"):
        f = memory.MEMORY / name
        if not f.exists():
            f.write_text(f"# {name}\n")
    bridges = _ensure_bridges()
    if bridges:
        print(f"bridges: {', '.join(bridges)}")

    # 4. Validate config schemas (fail fast on misconfiguration).
    try:
        warns = schema.validate_all()
        for w in warns:
            print(f"[warn] schema: {w}")
    except schema.SchemaError as e:
        print(f"[error] config schema invalid: {e}")
        return 2

    # 5. Validate that models declared in routing.yaml are actually available.
    missing = router.missing_local_models()
    for m in missing:
        print(f"[warn] declared model '{m}' not in Ollama (run `ollama pull {m}`)")

    logger.log("init",
               profile=profile["execution_mode"],
               ram_mb=res.ram_total_mb,
               cpu=res.cpu_count,
               gpu_mb=res.gpu_vram_total_mb,
               bridges=len(bridges),
               missing_models=missing)
    print("init: ok")
    return 0


def _maybe_refresh_profile() -> str | None:
    """If current RAM/CPU diverges >20% from recorded profile, regenerate it.
    Returns the new execution_mode if refreshed, else None."""
    profile_path = ROOT / "runtime" / "system-profile.json"
    if not profile_path.exists():
        return None
    try:
        cur = json.loads(profile_path.read_text())
        recorded_ram = cur["hardware"]["ram_total_mb"]
    except Exception:
        return None
    res = resources.snapshot()
    if recorded_ram == 0:
        return None
    drift = abs(res.ram_total_mb - recorded_ram) / recorded_ram
    if drift > 0.20:
        new_profile = resources.generate_system_profile(res)
        profile_path.write_text(json.dumps(new_profile, indent=2))
        return new_profile["execution_mode"]
    return None


def _cmd_reindex(args) -> int:
    refreshed = _maybe_refresh_profile()
    if refreshed:
        print(f"[info] system profile refreshed: {refreshed}")
    globs = args.globs or ["**/*.py", "**/*.js", "**/*.jsx", "**/*.md"]
    paths: list[Path] = []
    for g in globs:
        paths.extend(PROJECT.glob(g))
    paths = [p for p in paths if ".agentic-flow" not in p.parts and "node_modules" not in p.parts]
    stats = memory.index_paths(paths)
    print(json.dumps(stats))
    return 0


def _cmd_run(args) -> int:
    if args.dry_run:
        from . import router as _r
        agent_cfg = orchestrator._load_agent(args.agent)[0]
        choice = _r.choose(agent_cfg["task"], force_tier=args.tier)
        print(json.dumps({
            "agent": args.agent, "task": agent_cfg["task"],
            "tier": choice.tier, "model": choice.model,
            "timeout_s": choice.timeout_s, "reason": choice.reason,
        }, indent=2))
        return 0
    out = orchestrator.run(args.agent, args.task, force_tier=args.tier)
    if args.json:
        print(json.dumps(out, indent=2))
    else:
        print(f"[{out['tier']}/{out['model']}] cached={out.get('cached')} "
              f"duration={out.get('duration_ms', 0)}ms")
        print(out["output"])
    return 0


def _cmd_status(_) -> int:
    """One-shot diagnostic: profile, budget, cache stats, recent runs."""
    profile_path = ROOT / "runtime" / "system-profile.json"
    if profile_path.exists():
        profile = json.loads(profile_path.read_text())
        print(f"profile: {profile['execution_mode']} "
              f"(ram={profile['hardware']['ram_total_mb']}MB, "
              f"cpu={profile['hardware']['cpu_count']}, "
              f"gpu={profile['hardware']['gpu_vram_mb']}MB)")
    else:
        print("profile: NOT GENERATED — run `af init`")

    res = resources.snapshot()
    print(f"now:     ram_free={res.ram_available_mb}MB load={res.cpu_load_1m} "
          f"ollama={'up' if res.ollama_running else 'DOWN'} "
          f"loaded={len(res.ollama_loaded_models)}")

    metrics_f = ROOT / "runtime" / "metrics.jsonl"
    if metrics_f.exists():
        import datetime
        today = datetime.date.today().isoformat()
        spent = 0.0; calls = 0; hits = 0; total_ms = 0
        for line in metrics_f.read_text().splitlines():
            try:
                r = json.loads(line)
                if r.get("date") == today:
                    calls += 1
                    spent += r.get("cost_usd", 0)
                    if r.get("cache_hit"): hits += 1
                    total_ms += r.get("duration_ms", 0)
            except Exception:
                continue
        avg = (total_ms // calls) if calls else 0
        print(f"today:   {calls} calls, ${spent:.4f}, avg={avg}ms, cache_hits={hits}")
    else:
        print("today:   no calls yet")

    lock_f = ROOT / "runtime" / "ollama.lock"
    if lock_f.exists():
        import time as _t
        age = int(_t.time() - lock_f.stat().st_mtime)
        print(f"lock:    held pid={lock_f.read_text().strip()} age={age}s")
    return 0


def _cmd_build(args) -> int:
    results = orchestrator.pipeline(args.feature)
    for r in results:
        print(f"- {r['agent']:18} {r['tier']:10} {r['model']:30} "
              f"in={r.get('input_tokens', 0)} out={r.get('output_tokens', 0)}")
    return 0


def _cmd_metrics(args) -> int:
    if getattr(args, "prometheus", False):
        print(prometheus.export(), end="")
        return 0
    f = ROOT / "runtime" / "metrics.jsonl"
    if not f.exists():
        print("no metrics yet"); return 0
    total = 0.0
    by_tier: dict[str, float] = {}
    by_task: dict[str, int] = {}
    for line in f.read_text().splitlines():
        r = json.loads(line)
        total += r["cost_usd"]
        by_tier[r["tier"]] = by_tier.get(r["tier"], 0) + r["cost_usd"]
        by_task[r["task"]] = by_task.get(r["task"], 0) + 1
    print(f"total_usd: {total:.4f}")
    print(f"by_tier: {json.dumps(by_tier)}")
    print(f"calls_by_task: {json.dumps(by_task)}")
    return 0


def _cmd_warmup(args) -> int:
    roles = args.roles.split(",") if args.roles else None
    results = warmup.warm(roles)
    for role, info in results.items():
        status = "ok" if info.get("ok") else "FAIL"
        print(f"  {role:12} {info.get('model', '?'):30} {status}  {info.get('msg', '')}")
    return 0 if all(r.get("ok") for r in results.values()) else 1


def _cmd_resources(_) -> int:
    res = resources.snapshot()
    print(f"ram: {res.ram_available_mb}/{res.ram_total_mb} MB free ({res.ram_used_pct}% used)")
    print(f"cpu: {res.cpu_count} cores, load={res.cpu_load_1m}")
    if res.gpu_vram_total_mb:
        print(f"gpu: {res.gpu_vram_free_mb}/{res.gpu_vram_total_mb} MB VRAM free")
    else:
        print("gpu: not detected (CPU inference)")
    print(f"ollama: {'running' if res.ollama_running else 'DOWN'}")
    if res.ollama_loaded_models:
        print(f"loaded_models: {', '.join(res.ollama_loaded_models)}")
    else:
        print("loaded_models: none (cold-start expected)")
    print(f"can_load_model: {res.can_load_model}")
    print(f"pressure: ram={res.ram_pressure} cpu={res.cpu_pressure}")
    return 0


def _cmd_doctor(_) -> int:
    """End-to-end diagnostic: schema, profile, Ollama, models, lock state, recent errors."""
    rc = 0
    print("=== schema ===")
    try:
        warns = schema.validate_all()
        if warns:
            for w in warns:
                print(f"  warn: {w}")
        else:
            print("  ok")
    except schema.SchemaError as e:
        print(f"  ERROR: {e}")
        rc = 1

    print("=== resources ===")
    res = resources.snapshot()
    print(f"  ram: {res.ram_available_mb}/{res.ram_total_mb}MB ({res.ram_used_pct}% used)")
    print(f"  cpu: load_1m={res.cpu_load_1m} cores={res.cpu_count}")
    print(f"  gpu: {res.gpu_vram_total_mb}MB total" if res.gpu_vram_total_mb else "  gpu: none")
    print(f"  ollama: {'up' if res.ollama_running else 'DOWN'}")
    if not res.ollama_running:
        rc = 1

    print("=== models ===")
    missing = router.missing_local_models()
    if missing:
        for m in missing:
            print(f"  MISSING: {m}  -> ollama pull {m}")
        rc = 1
    else:
        print("  all declared models present")
    if res.ollama_loaded_models:
        print(f"  loaded (hot): {', '.join(res.ollama_loaded_models)}")

    print("=== lock ===")
    lock_f = ROOT / "runtime" / "ollama.lock"
    if lock_f.exists():
        import time as _t
        age = int(_t.time() - lock_f.stat().st_mtime)
        print(f"  held: pid={lock_f.read_text().strip()} age={age}s")
    else:
        print("  free")

    print("=== logs ===")
    log_dir = ROOT / "runtime" / "logs"
    if log_dir.exists():
        files = sorted(log_dir.glob("*.jsonl"))
        print(f"  files: {len(files)} (latest: {files[-1].name if files else 'none'})")
    else:
        print("  no logs yet")
    return rc


def _cmd_pull(args) -> int:
    """Pull missing models declared in routing.yaml from Ollama."""
    import subprocess
    missing = router.missing_local_models()
    if not missing:
        print("all declared models already present")
        return 0
    targets = [args.model] if args.model else missing
    for m in targets:
        print(f"==> ollama pull {m}")
        rc = subprocess.call(["ollama", "pull", m])
        if rc != 0:
            print(f"[error] failed to pull {m}")
            return rc
    # Refresh detection.
    detect_local.main()
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="af", description="agentic-flow: hybrid local/cloud agentic pipeline")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init").set_defaults(func=_cmd_init)

    r = sub.add_parser("reindex"); r.add_argument("--globs", nargs="*"); r.set_defaults(func=_cmd_reindex)

    rn = sub.add_parser("run")
    rn.add_argument("agent")
    rn.add_argument("task")
    rn.add_argument("--tier", choices=["local", "cloud-mid", "cloud-high"])
    rn.add_argument("--json", action="store_true")
    rn.add_argument("--dry-run", action="store_true",
                    help="Show which model would be picked without calling it")
    rn.set_defaults(func=_cmd_run)

    b = sub.add_parser("build"); b.add_argument("feature"); b.set_defaults(func=_cmd_build)
    mt = sub.add_parser("metrics", help="cost/usage summary or Prometheus export")
    mt.add_argument("--prometheus", action="store_true",
                    help="emit Prometheus text format instead of summary")
    mt.set_defaults(func=_cmd_metrics)
    sub.add_parser("resources").set_defaults(func=_cmd_resources)
    sub.add_parser("status").set_defaults(func=_cmd_status)
    sub.add_parser("doctor").set_defaults(func=_cmd_doctor)

    pl = sub.add_parser("pull", help="ollama pull for missing declared models")
    pl.add_argument("model", nargs="?")
    pl.set_defaults(func=_cmd_pull)

    wm = sub.add_parser("warmup", help="pre-load hot Ollama models")
    wm.add_argument("--roles", help="comma-separated roles (default: coder-fast,embed)")
    wm.set_defaults(func=_cmd_warmup)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
