"""Router: dada una task, selecciona modelo según routing.yaml + disponibilidad local + budget + recursos."""
from __future__ import annotations
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from . import resources

ROOT = Path(__file__).resolve().parents[1]
ROUTING = ROOT / "config" / "routing.yaml"
BUDGET = ROOT / "config" / "budget.yaml"
LOCAL_MODELS = ROOT / "runtime" / "local-models.json"
SYSTEM_PROFILE = ROOT / "runtime" / "system-profile.json"
METRICS = ROOT / "runtime" / "metrics.jsonl"


@dataclass(frozen=True)
class ModelChoice:
    tier: str
    provider: str
    model: str
    endpoint: str | None
    context_window: int
    timeout_s: int
    reason: str


def _load_yaml(p: Path) -> dict:
    return yaml.safe_load(p.read_text())


def _spent_today_usd() -> float:
    if not METRICS.exists():
        return 0.0
    today = __import__("datetime").date.today().isoformat()
    total = 0.0
    for line in METRICS.read_text().splitlines():
        try:
            r = json.loads(line)
            if r.get("date") == today:
                total += r.get("cost_usd", 0.0)
        except Exception:
            pass
    return total


def _local_available() -> dict:
    if not LOCAL_MODELS.exists():
        return {"models": [], "has_code_model": False}
    return json.loads(LOCAL_MODELS.read_text())


def _load_profile() -> dict | None:
    """Load system profile generated by `af init`. Returns None if not yet generated."""
    if not SYSTEM_PROFILE.exists():
        return None
    try:
        return json.loads(SYSTEM_PROFILE.read_text())
    except Exception:
        return None


def _pick_local(routing: dict, want: str, sys_res: resources.SystemResources | None = None
                ) -> tuple[str, str, int] | None:
    """want: modelo declarado en tiers.local.models (coder-fast, coder, reason, embed, general)."""
    local = _local_available()
    models = local.get("models", [])
    if not models:
        return None

    declared = routing["tiers"]["local"]["models"].get(want)
    candidates: list[tuple[str, str, int]] = []

    if declared:
        short = declared.split(":")[0]
        for m in models:
            if m["name"].startswith(short):
                candidates.append((m["name"], m["endpoint"], m["context_window"]))

    if not candidates:
        # fallback: buscar por especialidad según want
        specialty_map = {"coder-fast": "code", "coder": "code", "coder-heavy": "code",
                         "reason": "reason", "embed": "embedding", "general": "general"}
        target_spec = specialty_map.get(want, "general")
        for m in models:
            if m["specialty"] == target_spec:
                candidates.append((m["name"], m["endpoint"], m["context_window"]))

    if not candidates:
        candidates.append((models[0]["name"], models[0]["endpoint"], models[0]["context_window"]))

    # Prefer model already loaded in Ollama (avoids cold-start).
    if sys_res and sys_res.ollama_loaded_models:
        for name, ep, ctx in candidates:
            if sys_res.model_is_loaded(name):
                return name, ep, ctx

    return candidates[0]


def choose(task: str, required_ctx: int = 4096, force_tier: str | None = None) -> ModelChoice:
    routing = _load_yaml(ROUTING)
    budget = _load_yaml(BUDGET)
    profile = _load_profile()
    rule = routing["tasks"].get(task)
    if not rule:
        raise ValueError(f"task '{task}' not registered in routing.yaml")

    # Take resource snapshot for informed routing.
    sys_res = resources.snapshot()

    over_budget = _spent_today_usd() >= budget["limits"]["daily_usd"]
    chain = [force_tier] if force_tier else [rule["tier"], *rule.get("fallback", [])]
    task_model_want = rule.get("model", "coder")

    for tier in chain:
        if not tier:
            continue
        if over_budget and tier.startswith("cloud"):
            continue

        if tier == "local":
            # Skip local if Ollama is down or system under heavy pressure.
            if not sys_res.ollama_running:
                continue
            if sys_res.ram_pressure and sys_res.cpu_pressure:
                continue

            picked = _pick_local(routing, task_model_want, sys_res)
            if not picked or picked[2] < required_ctx:
                continue

            # Use profile conditions if available (generated by `af init`).
            if profile:
                model_conds = profile.get("model_conditions", {})
                short_name = picked[0].split(":")[0]
                cond = model_conds.get(picked[0]) or model_conds.get(short_name)
                if cond and not cond.get("suitable", True):
                    continue  # Model not suitable for this hardware.
                base_timeout = (cond or {}).get("timeout_s",
                               profile["conditions"]["recommended_timeout_s"])
            else:
                base_timeout = int(routing["tiers"]["local"].get("timeout_s", 300))

            # Add cold-start buffer if model not currently loaded.
            if not sys_res.model_is_loaded(picked[0]):
                base_timeout += 120
            return ModelChoice("local", "ollama", picked[0], picked[1], picked[2],
                               base_timeout,
                               reason=f"local:{task_model_want} available"
                                      f" (loaded={sys_res.model_is_loaded(picked[0])})")
        else:
            models = routing["tiers"][tier]["models"]
            timeout_s = int(routing["tiers"][tier].get("timeout_s", 180))
            return ModelChoice(tier, "cloud", models[0], None, 128000,
                               timeout_s,
                               reason=f"tier={tier}")

    return ModelChoice("local", "ollama",
                       routing["tiers"]["local"]["models"]["coder"],
                       routing["tiers"]["local"]["base_url"], 8192,
                       int(routing["tiers"]["local"].get("timeout_s", 300)),
                       reason="fallback forced local (budget/availability)")


def validate_declared_models() -> list[str]:
    """Cross-check models declared in routing.yaml against detected local models.
    Returns list of warnings (empty if all good). Called from `af init`."""
    routing = _load_yaml(ROUTING)
    local = _local_available()
    detected = {m["name"].split(":")[0] for m in local.get("models", [])}
    warnings = []
    for role, full in routing["tiers"]["local"]["models"].items():
        short = full.split(":")[0]
        if short not in detected:
            warnings.append(f"declared local model '{full}' (role={role}) not found in Ollama")
    return warnings


def missing_local_models() -> list[str]:
    """Returns full model names declared in routing.yaml but absent from Ollama."""
    routing = _load_yaml(ROUTING)
    local = _local_available()
    detected = {m["name"].split(":")[0] for m in local.get("models", [])}
    missing = []
    for _role, full in routing["tiers"]["local"]["models"].items():
        if full.split(":")[0] not in detected:
            missing.append(full)
    return missing


def estimate_cost(model: str, input_tokens: int, output_tokens: int,
                  cache_creation_tokens: int = 0, cache_read_tokens: int = 0) -> float:
    """Cost in USD. Applies Anthropic prompt-cache multipliers when provided
    (cache_creation=1.25x input, cache_read=0.10x input by default)."""
    budget = _load_yaml(BUDGET)
    table = budget.get("cost_table_usd_per_1m_tokens", {})
    rates = table.get(model, {"input": 0, "output": 0})
    pc = budget.get("prompt_cache", {})
    creation_mult = pc.get("cache_creation_multiplier", 1.25)
    read_mult = pc.get("cache_read_multiplier", 0.10)
    cost = (
        input_tokens * rates["input"]
        + output_tokens * rates["output"]
        + cache_creation_tokens * rates["input"] * creation_mult
        + cache_read_tokens * rates["input"] * read_mult
    )
    return cost / 1_000_000


def record(task: str, choice: ModelChoice, input_tokens: int, output_tokens: int,
           duration_ms: int = 0, cache_hit: bool = False,
           cache_creation_tokens: int = 0, cache_read_tokens: int = 0) -> None:
    import datetime as _dt
    METRICS.parent.mkdir(parents=True, exist_ok=True)
    rec: dict[str, Any] = {
        "date": _dt.date.today().isoformat(),
        "ts": _dt.datetime.now(_dt.timezone.utc).isoformat().replace("+00:00", "Z"),
        "task": task,
        "tier": choice.tier,
        "model": choice.model,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "cache_creation_tokens": cache_creation_tokens,
        "cache_read_tokens": cache_read_tokens,
        "cost_usd": estimate_cost(choice.model, input_tokens, output_tokens,
                                  cache_creation_tokens, cache_read_tokens),
        "duration_ms": duration_ms,
        "cache_hit": cache_hit,
        "reason": choice.reason,
    }
    with METRICS.open("a") as f:
        f.write(json.dumps(rec) + "\n")
